version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-2
      - REPOSITORY_URI=public.ecr.aws/c7l4l0y6/arthur-helloworld
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/c7l4l0y6/arthur-helloworld:latest
      - docker push public.ecr.aws/c7l4l0y6/arthur-helloworld:latest
      - echo Writing image definitions file...
      - printf '[{"name”:"ArthurContainer","imageUri":"%s"}]' public.ecr.aws/c7l4l0y6/arthur-helloworld:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
